train:
  _target_: src.datasets.ASVPoofDataset
  protocol_name: "train.trn"
  name: "train"
val:
  _target_: src.datasets.ASVPoofDataset
  protocol_name: "dev.trl"
  name: "dev"
test:
  _target_: src.datasets.ASVPoofDataset
  protocol_name: "eval.trl"
  name: "eval"
