defaults:
  - model: lcnn
  - writer: cometml
  - metrics: eer
  - datasets: dataset
  - dataloader: example
  - _self_
optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-3
lr_scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  optimizer: ${optimizer._target_}
  max_lr: 1e-3
  epochs: 25
  pct_start: 0.2
  anneal_strategy: 'cos'
  patience: 3
loss_function:
  _target_: src.loss.ExampleLoss
trainer:
  log_step: 1
  n_epochs: 25
  epoch_len: 500
  device_tensors: ["data_object", "labels"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: True # if True, will override the previous run with the same name
  monitor: "min EER" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  seed: 1
